# Generated by Django 3.0.4 on 2020-03-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('item_image_no', models.BigAutoField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=64)),
                ('item_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_item', to='api.Item')),
            ],
        ),
    ]
